import test from 'node:test';
import assert from 'node:assert/strict';
import { PrismaClient, UserRole } from '@prisma/client';
import { CameraGroupsService } from '../src/camera-groups/camera-groups.service';
import { AccessControlService } from '../src/access-control/access-control.service';

const url = process.env.DRAC_E2E_DATABASE_URL;
test('quatro grupos: banco real, acessos, concorrência e retenção', { skip: !url && 'Exige banco de testes separado' }, async () => {
  const db = new PrismaClient({ datasources: { db: { url } } });
  const access = new AccessControlService(db as any);
  const groups = new CameraGroupsService(db as any, access);
  const prefix = `four-groups-${process.pid}-`;
  const gid = (n: number) => `${prefix}g${n}`;
  const cid = `${prefix}camera`;
  const uid = `${prefix}viewer`;
  try {
    await db.cameraGroup.createMany({ data: Array.from({ length: 7 }, (_, i) => ({ id: gid(i), name: gid(i), retentionDays: i === 0 ? 9 : 3 })) });
    await db.user.create({ data: { id: uid, username: uid, name: uid, passwordHash: 'test-only', role: UserRole.VIEWER } });
    await db.camera.create({ data: { id: cid, name: cid, ip: '127.0.0.1', username: 'test', passwordEncrypted: 'test-only', groupId: gid(0) } });
    assert.equal((await db.camera.findUniqueOrThrow({ where: { id: cid }, include: { groups: true } })).groups.length, 1);
    await groups.addCamera(gid(1), cid);
    await groups.addCamera(gid(2), cid);
    const attempts = await Promise.allSettled([groups.addCamera(gid(3), cid), groups.addCamera(gid(4), cid)]);
    assert.equal(attempts.filter((r) => r.status === 'fulfilled').length, 1, 'Somente uma vaga pode ser ocupada');
    let camera = await db.camera.findUniqueOrThrow({ where: { id: cid }, include: { groups: true } });
    assert.equal(camera.groups.length, 4);
    assert.equal(camera.groupId, gid(0));
    await groups.addCamera(gid(1), cid);
    await assert.rejects(groups.addCamera(gid(5), cid), /4 grupos/);
    await assert.rejects(db.camera.update({ where: { id: cid }, data: { groups: { connect: { id: gid(5) } } } }), /4 grupos/);
    await db.cameraPermission.create({ data: { userId: uid, groupId: gid(1), level: 'VIEW' } });
    const user = { id: uid, role: UserRole.VIEWER, name: uid, email: '' };
    assert.deepEqual(await access.getAccessibleCameraIds(user), [cid]);
    assert.equal(await access.canViewCamera(user, cid), true);
    assert.equal((await groups.list(user))[0].cameras[0].id, cid);
    await db.cameraGroup.update({ where: { id: gid(1) }, data: { accessStatus: 'SUSPENDED' } });
    assert.equal(await access.canViewCamera(user, cid), false);
    assert.deepEqual(await access.getAccessibleCameraIds(user), []);
    await db.cameraGroup.update({ where: { id: gid(1) }, data: { accessStatus: 'ACTIVE' } });
    await db.cameraGroup.update({ where: { id: gid(1) }, data: { accessStatus: 'RESTRICTED' } });
    assert.equal(await access.canViewCamera(user, cid), true);
    assert.equal(await access.canPlaybackCamera(user, cid), false);
    assert.deepEqual(await access.getPlaybackCameraIds(user), []);
    await db.cameraGroup.update({ where: { id: gid(1) }, data: { accessStatus: 'ACTIVE' } });
    assert.equal(await access.canPlaybackCamera(user, cid), true);
    assert.deepEqual(await access.getPlaybackCameraIds(user), [cid]);
    await groups.setRetentionForGroup(gid(1), 1, [cid]);
    assert.equal((await db.camera.findUniqueOrThrow({ where: { id: cid } })).retentionFollowsGroup, true);
    await groups.removeCamera(gid(0), cid);
    camera = await db.camera.findUniqueOrThrow({ where: { id: cid }, include: { groups: true } });
    assert.equal(camera.groups.length, 3);
    assert.equal(camera.groups.some((g) => g.id === gid(1)), true);
    assert.equal(camera.retentionDays, 9);
    assert.equal(camera.retentionFollowsGroup, false);
    await groups.addCamera(gid(5), cid);
    assert.equal(await access.canViewCamera(user, cid), true);
    await groups.removeCamera(gid(1), cid);
    assert.equal(await access.canViewCamera(user, cid), false);
    camera = await db.camera.findUniqueOrThrow({ where: { id: cid }, include: { groups: true } });
    assert.equal(camera.groups.length, 3);
    await groups.softDelete(gid(5));
    camera = await db.camera.findUniqueOrThrow({ where: { id: cid }, include: { groups: true } });
    assert.equal(camera.groups.length, 2);
    await db.camera.update({ where: { id: cid }, data: { groupId: gid(6) } });
    camera = await db.camera.findUniqueOrThrow({ where: { id: cid }, include: { groups: true } });
    assert.equal(camera.groups.some((g) => g.id === gid(6)), true, 'Edição legada mantém a relação múltipla sincronizada');
    const privateId = `${prefix}private`;
    await db.camera.create({ data: { id: privateId, name: privateId, ip: '127.0.0.1', username: 'test', passwordEncrypted: 'test-only', isPrivate: true, ownerUserId: uid } });
    await assert.rejects(groups.addCamera(gid(2), privateId), /particulares/);
  } finally {
    await db.camera.deleteMany({ where: { id: { startsWith: prefix } } });
    await db.user.deleteMany({ where: { id: uid } });
    await db.cameraGroup.deleteMany({ where: { id: { startsWith: prefix } } });
    await db.$disconnect();
  }
});
