'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {EventEmitter}=require('node:events');
const {launchCommand,deliverInstaller,secretLog,READY,SUDO_PROMPT}=require('../src/remote-install-runtime');
function stream(){const s=new EventEmitter();s.stderr=new EventEmitter();s.writes=[];s.write=x=>s.writes.push(x);s.end=x=>s.writes.push(x);s.close=()=>s.emit('close',1);return s;}
function attach(s){const logs=[],failures=[];const state=deliverInstaller(s,{username:'operator',password:'synthetic-secret',script:'echo synthetic-installer',onLog:x=>logs.push(x),onFailure:x=>failures.push(x),readyMs:2000});return {state,logs,failures};}
test('SSH argv has no credentials or installer script; sudo only for non-root',()=>{assert.match(launchCommand('operator'),/^sudo -S/);assert.doesNotMatch(launchCommand('root'),/sudo/);assert.doesNotMatch(launchCommand('operator'),/synthetic-secret|echo synthetic-installer/);});
test('root/ready sends script once, without sending sudo password',()=>{const s=stream(),r=attach(s);s.emit('data',READY+'\n');s.emit('data','normal log\n');assert.equal(r.state.started,true);assert.equal(s.writes.length,1);assert.match(s.writes[0],/set \+x/);assert.doesNotMatch(s.writes[0],/synthetic-secret/);s.emit('close',0);});
test('split sudo and ready markers work without pty echo',()=>{const s=stream(),r=attach(s);s.stderr.emit('data',SUDO_PROMPT.slice(0,10));s.stderr.emit('data',SUDO_PROMPT.slice(10));assert.deepEqual(s.writes,['synthetic-secret\n']);s.emit('data',READY.slice(0,7));s.emit('data',READY.slice(7)+'\n');assert.equal(r.state.started,true);assert.equal(s.writes.length,2);assert.equal(r.failures.length,0);assert.doesNotMatch(r.logs.join(''),/DRAC_REMOTE_SUDO|synthetic-secret/);s.emit('close',0);});
test('wrong sudo password fails without sending installer',()=>{const s=stream(),r=attach(s);s.stderr.emit('data',SUDO_PROMPT);s.stderr.emit('data',SUDO_PROMPT);assert.equal(r.failures.length,1);assert.equal(r.state.started,false);assert.equal(s.writes.length,1);});
test('timeout closes only its channel',async()=>{const s=stream();let failed=false,closed=false;s.close=()=>{closed=true;s.emit('close',1);};deliverInstaller(s,{username:'operator',password:'synthetic',script:'echo fixture',onLog:()=>{},onFailure:()=>{failed=true;},readyMs:10});await new Promise(r=>setTimeout(r,25));assert.equal(failed,true);assert.equal(closed,true);assert.equal(s.writes.length,0);});
test('log redacts credentials split at every possible chunk boundary',()=>{const key='synthetic-secret';for(let i=1;i<key.length;i++){const out=[];const log=secretLog(x=>out.push(x),[key]);log.push('prefix '+key.slice(0,i));log.push(key.slice(i)+' suffix');log.flush();assert.equal(out.join(''),'prefix •••••• suffix');}});
