'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const fs=require('node:fs/promises');const path=require('node:path');
const {startCentral}=require('./helpers/central-server');
async function fixture(t,cidrs='192.0.2.0/24'){const c=await startCentral();t.after(()=>c.stop());const r=await fetch(c.base+'/api/admin/provision',{method:'POST',headers:c.adminHeaders(),body:JSON.stringify({installationId:'pilot',customerName:'Pilot',serverAddress:'192.0.2.10',cameraAllowedCidrs:cidrs})});assert.equal(r.status,201);return c;}
function run(c,extra={}){return fetch(c.base+'/api/admin/installations/pilot/remote-install',{method:'POST',headers:c.adminHeaders(),body:JSON.stringify({host:'127.0.0.1',port:1,username:'operator',password:'synthetic-ssh-password',...extra})});}
test('missing networks rejects before connecting instead of hanging at installer prompt',async t=>{const c=await fixture(t,'');const r=await run(c);assert.equal(r.status,400);assert.equal((await r.json()).error,'missing_camera_networks');});
test('SSH username, port and multiline password are rejected before connecting',async t=>{const c=await fixture(t);for(const extra of [{username:'bad;name'},{port:70000},{password:'line\nbreak'}])assert.equal((await run(c,extra)).status,400);});
test('candidate must include its own immutable commit, hash and explicit purpose',async t=>{const c=await fixture(t);for(const validationRelease of [{purpose:'clean-install-validation',commit:'2'.repeat(40)},{purpose:'clean-install-validation',commit:'main',installerSha256:'b'.repeat(64)},{purpose:'other',commit:'2'.repeat(40),installerSha256:'b'.repeat(64)}])assert.equal((await run(c,{validationRelease})).status,503);});
test('pilot does not promote fleet release and never persists bootstrap/SSH passwords',async t=>{const c=await fixture(t);const r=await run(c,{validationRelease:{purpose:'clean-install-validation',commit:'2'.repeat(40),installerSha256:'b'.repeat(64)}});assert.equal(r.status,202);const d=await r.json();assert.equal(d.initialAccess.username,'admin');assert.ok(d.initialAccess.password.length>=12);await new Promise(r=>setTimeout(r,150));const disk=await fs.readFile(path.join(c.dir,'installations.json'),'utf8');assert.ok(!disk.includes(d.initialAccess.password));assert.ok(!disk.includes('synthetic-ssh-password'));const data=JSON.parse(disk);assert.equal(data.release,undefined);assert.equal(data.installations.pilot.installerArtifact.id,'1'.repeat(40));assert.ok(data.auditEvents.some(x=>x.validationRelease?.commit==='2'.repeat(40)));});
