listen 1935;
max_connections 20;
daemon off;
srs_log_tank console;
vhost __defaultVhost__ {
    tcp_nodelay on;
    min_latency on;
    forward {
        enabled on;
        destination drac-validation-sink:1935;
    }
}
